### ISSUE TITLE
Bug in Reiter  "Übersicht" bei den Beteiligten

### ISSUE THREAD

**Issue by mmellenthin** [jlawyerorg/j-lawyer-templates#13]
Ubut Version, aktuell ( 10.05.2024)

Im Reiter "Übersicht" bei den BEteiligten  werden die Kontaktdaten des letzten geöffneten Reiters "Kontakt" angezeigt und nicht des aktuellenen Beteiligten.

Wenn ich mir die Kontaktdaten eines Beteiligten ansehe z.B. unter Reiter "Kontakt" und dann in eine andere Akte wechsel, wird dort bei einem ganz anderen Beteiligten im Reiter " Übersicht" immer noch die Daten des Beteiligten aus der Vorakte angezeigt. Gehe ich dann in dieser Akte auf einen Reiter steht auch in der Übersicht die neuen Daten.

**Comment by j-dimension** [comment]
Bereits bearbietet via https://github.com/jlawyerorg/j-lawyer-org/issues/2442
